artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/prishasawhney/mushroom-dataset
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_data_dir: artifacts/data_ingestion/mushroom_cleaned.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/mushroom_cleaned.csv
<<<<<<< HEAD
=======


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/mushroom_cleaned.csv
>>>>>>> b57c7bf19c5d2a14e985afa12f97e0bde0160f0a
  categorical_feature_path : categorical.joblib
  categorical_json_path : categorical.json
